import { DEFAULT_PRIVACY, Adventure, Thread, User } from './types';

export const ME_ID = 'u-vincent';

export const users: Record<string, User> = {
  [ME_ID]: {
    id: ME_ID,
    name: 'Vincent Macharia',
    initials: 'VM',
    role: 'Explorer',
    location: 'Nairobi',
    avatarHue: 205,
    username: 'vincentm',
    bio: 'Weekend hiker, always up for sunrise starts.',
    interests: ['Hiking', 'Photography'],
    adventureCategories: ['Hike'],
    preferredDifficulty: 'Moderate',
    preferredSocialLevel: 'Social',
    preferredPace: 'Moderate',
    preferredIntensity: 'Medium',
    experienceLevel: 'Intermediate',
    tags: ['Photography', 'Solo adventures'],
    completedAdventuresCount: 4,
    connectionsCount: 2,
    crewIds: [],
    privacy: DEFAULT_PRIVACY,
  },
  'u-tom': {
    id: 'u-tom',
    name: 'Tom Wanjiru',
    initials: 'TW',
    role: 'Organizer',
    location: 'Naivasha',
    avatarHue: 205,
    username: 'tomw',
    bio: 'Runs weekend road trips around the Rift Valley.',
    interests: ['Road trips', 'Cycling'],
    adventureCategories: ['Road trip'],
    preferredDifficulty: 'Moderate',
    preferredSocialLevel: 'Very Social',
    preferredPace: 'Moderate',
    preferredIntensity: 'Medium',
    experienceLevel: 'Advanced',
    tags: ['Networking', 'Families'],
    completedAdventuresCount: 18,
    connectionsCount: 34,
    crewIds: [],
    privacy: DEFAULT_PRIVACY,
  },
  'u-kevin': {
    id: 'u-kevin',
    name: 'Kevin Otieno',
    initials: 'KO',
    role: 'Explorer',
    location: 'Nairobi',
    avatarHue: 28,
    username: 'kevino',
    bio: 'New to hiking, learning the trails around Nairobi.',
    interests: ['Hiking'],
    adventureCategories: ['Hike'],
    preferredDifficulty: 'Beginner',
    preferredSocialLevel: 'Social',
    preferredPace: 'Relaxed',
    preferredIntensity: 'Low',
    experienceLevel: 'Beginner',
    tags: [],
    completedAdventuresCount: 1,
    connectionsCount: 0,
    crewIds: [],
    privacy: DEFAULT_PRIVACY,
  },
  'u-amina': {
    id: 'u-amina',
    name: 'Amina Kones',
    initials: 'AK',
    role: 'Explorer',
    location: 'Nairobi',
    avatarHue: 28,
    username: 'aminak',
    bio: 'Forest walks and quiet trails over crowded ones.',
    interests: ['Hiking', 'Nature'],
    adventureCategories: ['Hike'],
    preferredDifficulty: 'Beginner',
    preferredSocialLevel: 'Quiet',
    preferredPace: 'Relaxed',
    preferredIntensity: 'Low',
    experienceLevel: 'Intermediate',
    tags: ['Solo adventures'],
    completedAdventuresCount: 6,
    connectionsCount: 3,
    crewIds: [],
    privacy: DEFAULT_PRIVACY,
  },
  'u-brian': {
    id: 'u-brian',
    name: 'Brian K.',
    initials: 'BK',
    role: 'Explorer',
    location: 'Nairobi',
    avatarHue: 150,
    username: 'briank',
    bio: 'Hikes on weekends, road trips whenever possible.',
    interests: ['Hiking', 'Road trips'],
    adventureCategories: ['Hike', 'Road trip'],
    preferredDifficulty: 'Moderate',
    preferredSocialLevel: 'Social',
    preferredPace: 'Moderate',
    preferredIntensity: 'Medium',
    experienceLevel: 'Intermediate',
    tags: ['Couples'],
    completedAdventuresCount: 3,
    connectionsCount: 1,
    crewIds: [],
    privacy: DEFAULT_PRIVACY,
  },
};

export const initialAdventures: Adventure[] = [
  {
    id: 'a-ngong',
    title: 'Ngong Hills sunrise hike',
    type: 'Hike',
    difficulty: 'Moderate',
    dateLabel: 'Sat, Sep 12',
    meetingTime: '6:00am',
    location: 'Ngong Hills, Kajiado',
    priceKsh: 1500,
    spotsTotal: 1,
    spotsFilled: 1,
    organizerId: ME_ID,
    participantIds: ['u-brian'],
    guidelines: ['No alcohol', 'Bring 2L water'],
    likedByMe: false,
    likeCount: 12,
    coordinate: { x: 0.42, y: 0.58 },
  },
  {
    id: 'a-naivasha',
    title: 'Naivasha road trip',
    type: 'Road trip',
    difficulty: 'Moderate',
    dateLabel: 'Sun, Sep 13',
    meetingTime: '7:00am',
    location: 'Lake Naivasha',
    priceKsh: 4500,
    spotsTotal: 20,
    spotsFilled: 11,
    organizerId: 'u-tom',
    participantIds: ['u-kevin', 'u-brian'],
    guidelines: ['Carpool meets at Total station', 'Bring a valid ID'],
    likedByMe: false,
    likeCount: 7,
    coordinate: { x: 0.22, y: 0.34 },
  },
  {
    id: 'a-karura',
    title: 'Karura Forest evening walk',
    type: 'Hike',
    difficulty: 'Beginner',
    dateLabel: 'Wed, Sep 16',
    meetingTime: '5:30pm',
    location: 'Karura Forest, Nairobi',
    priceKsh: 300,
    spotsTotal: 15,
    spotsFilled: 4,
    organizerId: 'u-amina',
    participantIds: [],
    guidelines: ['No littering', 'Closed shoes recommended'],
    likedByMe: true,
    likeCount: 3,
    coordinate: { x: 0.6, y: 0.22 },
  },
  {
    id: 'a-amboseli',
    title: 'Amboseli weekend safari',
    type: 'Road trip',
    difficulty: 'Challenging',
    dateLabel: 'Fri, Sep 25',
    meetingTime: '5:00am',
    location: 'Amboseli National Park',
    priceKsh: 12000,
    spotsTotal: 8,
    spotsFilled: 8,
    organizerId: 'u-tom',
    participantIds: [],
    guidelines: ['Passport or ID required', 'Full payment to organizer before departure'],
    likedByMe: false,
    likeCount: 21,
    coordinate: { x: 0.75, y: 0.7 },
  },
];

export const initialThreads: Thread[] = [
  {
    id: 't-kevin',
    adventureId: 'a-ngong',
    otherUserId: 'u-kevin',
    unread: true,
    messages: [
      {
        id: 'm1',
        threadId: 't-kevin',
        senderId: 'u-kevin',
        text: 'Should I bring a headlamp?',
        status: 'sent',
        createdAt: Date.now() - 1000 * 60 * 40,
      },
    ],
  },
  {
    id: 't-tom',
    adventureId: 'a-naivasha',
    otherUserId: 'u-tom',
    unread: false,
    messages: [
      {
        id: 'm2',
        threadId: 't-tom',
        senderId: 'u-tom',
        text: 'We meet at the Total station, 7am.',
        status: 'sent',
        createdAt: Date.now() - 1000 * 60 * 60 * 5,
      },
      {
        id: 'm3',
        threadId: 't-tom',
        senderId: ME_ID,
        text: 'Sounds good, see you then.',
        status: 'sent',
        createdAt: Date.now() - 1000 * 60 * 60 * 4,
      },
    ],
  },
  {
    id: 't-amina',
    adventureId: 'a-ngong',
    otherUserId: 'u-amina',
    unread: false,
    messages: [
      {
        id: 'm4',
        threadId: 't-amina',
        senderId: 'u-amina',
        text: 'Hey! Excited to have you on the hike Saturday.',
        status: 'sent',
        createdAt: Date.now() - 1000 * 60 * 60 * 2,
      },
    ],
  },
];
